site:
  name: PME + AI
  site: 'https://guillaume.barillot.me'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: PME + AI
    template: '%s — PME + AI'
  description: 'Automatisation de processus et de workflows pour les PME françaises.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: PME + AI
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: fr
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 8

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
